name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  project-deploy:
    runs-on: self-hosted

    steps:
    - name: Update Local Repo
      run: cd /home/azureuser/uptime-kuma && git fetch && git reset --hard 
    - name: Install Dependencies
      run: npm install
    - name: pm2 restart uptime-kuma

